# TCL File Generated by Component Editor 23.4
# Thu Mar 14 09:44:19 MYT 2024
# DO NOT MODIFY


# 
# emif_axi_adaptor_eagle "emif_axi_adaptor_eagle" v1.0
#  2024.03.14.09:44:19
# 
# 

# 
# request TCL package from ACDS 23.4
# 
package require -exact qsys 23.4


# 
# module emif_axi_adaptor_eagle
# 
set_module_property DESCRIPTION ""
set_module_property NAME emif_axi_adaptor_eagle
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME emif_axi_adaptor_eagle
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL emif_axi_handler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file emif_axi_handler.sv SYSTEM_VERILOG PATH emif_axi_handler.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL emif_axi_handler
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file emif_axi_handler.sv SYSTEM_VERILOG PATH emif_axi_handler.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk_i
# 
add_interface clk_i clock end
set_interface_property clk_i ENABLED true
set_interface_property clk_i EXPORT_OF ""
set_interface_property clk_i PORT_NAME_MAP ""
set_interface_property clk_i CMSIS_SVD_VARIABLES ""
set_interface_property clk_i SVD_ADDRESS_GROUP ""
set_interface_property clk_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk_i SV_INTERFACE_TYPE ""
set_interface_property clk_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk_i clk_i clk Input 1


# 
# connection point rst_n_i
# 
add_interface rst_n_i reset end
set_interface_property rst_n_i associatedClock clk_i
set_interface_property rst_n_i synchronousEdges DEASSERT
set_interface_property rst_n_i ENABLED true
set_interface_property rst_n_i EXPORT_OF ""
set_interface_property rst_n_i PORT_NAME_MAP ""
set_interface_property rst_n_i CMSIS_SVD_VARIABLES ""
set_interface_property rst_n_i SVD_ADDRESS_GROUP ""
set_interface_property rst_n_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_n_i SV_INTERFACE_TYPE ""
set_interface_property rst_n_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_n_i rst_n_i reset_n Input 1


# 
# connection point core_axi
# 
add_interface core_axi axi4 end
set_interface_property core_axi associatedClock clk_i
set_interface_property core_axi associatedReset rst_n_i
set_interface_property core_axi wakeupSignals false
set_interface_property core_axi uniqueIdSupport false
set_interface_property core_axi poison false
set_interface_property core_axi traceSignals false
set_interface_property core_axi readAcceptanceCapability 1
set_interface_property core_axi writeAcceptanceCapability 1
set_interface_property core_axi combinedAcceptanceCapability 1
set_interface_property core_axi readDataReorderingDepth 1
set_interface_property core_axi bridgesToMaster ""
set_interface_property core_axi dfhFeatureGuid 0
set_interface_property core_axi dfhGroupId 0
set_interface_property core_axi dfhParameterId ""
set_interface_property core_axi dfhParameterName ""
set_interface_property core_axi dfhParameterVersion ""
set_interface_property core_axi dfhParameterData ""
set_interface_property core_axi dfhParameterDataLength ""
set_interface_property core_axi dfhFeatureMajorVersion 0
set_interface_property core_axi dfhFeatureMinorVersion 0
set_interface_property core_axi dfhFeatureId 35
set_interface_property core_axi ENABLED true
set_interface_property core_axi EXPORT_OF ""
set_interface_property core_axi PORT_NAME_MAP ""
set_interface_property core_axi CMSIS_SVD_VARIABLES ""
set_interface_property core_axi SVD_ADDRESS_GROUP ""
set_interface_property core_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property core_axi SV_INTERFACE_TYPE ""
set_interface_property core_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port core_axi core_axi_arlock_i arlock Input 1
add_interface_port core_axi core_axi_arprot_i arprot Input 3
add_interface_port core_axi core_axi_arqos_i arqos Input 4
add_interface_port core_axi core_axi_arready_o arready Output 1
add_interface_port core_axi core_axi_arvalid_i arvalid Input 1
add_interface_port core_axi core_axi_araddr_i araddr Input 30
add_interface_port core_axi core_axi_arburst_i arburst Input 2
add_interface_port core_axi core_axi_arid_i arid Input 7
add_interface_port core_axi core_axi_arlen_i arlen Input 8
add_interface_port core_axi core_axi_arsize_i arsize Input 3
add_interface_port core_axi core_axi_aruser_i aruser Input 4
add_interface_port core_axi core_axi_rready_i rready Input 1
add_interface_port core_axi core_axi_rvalid_o rvalid Output 1
add_interface_port core_axi core_axi_rlast_o rlast Output 1
add_interface_port core_axi core_axi_rdata_o rdata Output 256
add_interface_port core_axi core_axi_rid_o rid Output 7
add_interface_port core_axi core_axi_rresp_o rresp Output 2
add_interface_port core_axi core_axi_ruser_o ruser Output 64
add_interface_port core_axi core_axi_awlock_i awlock Input 1
add_interface_port core_axi core_axi_awprot_i awprot Input 3
add_interface_port core_axi core_axi_awqos_i awqos Input 4
add_interface_port core_axi core_axi_awready_o awready Output 1
add_interface_port core_axi core_axi_awvalid_i awvalid Input 1
add_interface_port core_axi core_axi_awaddr_i awaddr Input 30
add_interface_port core_axi core_axi_awburst_i awburst Input 2
add_interface_port core_axi core_axi_awid_i awid Input 7
add_interface_port core_axi core_axi_awlen_i awlen Input 8
add_interface_port core_axi core_axi_awsize_i awsize Input 3
add_interface_port core_axi core_axi_awuser_i awuser Input 4
add_interface_port core_axi core_axi_wlast_i wlast Input 1
add_interface_port core_axi core_axi_wready_o wready Output 1
add_interface_port core_axi core_axi_wvalid_i wvalid Input 1
add_interface_port core_axi core_axi_wdata_i wdata Input 256
add_interface_port core_axi core_axi_wstrb_i wstrb Input 32
add_interface_port core_axi core_axi_wuser_i wuser Input 64
add_interface_port core_axi core_axi_bready_i bready Input 1
add_interface_port core_axi core_axi_bvalid_o bvalid Output 1
add_interface_port core_axi core_axi_bid_o bid Output 7
add_interface_port core_axi core_axi_bresp_o bresp Output 2


# 
# connection point emif_axi
# 
add_interface emif_axi axi4 start
set_interface_property emif_axi associatedClock clk_i
set_interface_property emif_axi associatedReset rst_n_i
set_interface_property emif_axi wakeupSignals false
set_interface_property emif_axi uniqueIdSupport false
set_interface_property emif_axi poison false
set_interface_property emif_axi traceSignals false
set_interface_property emif_axi readIssuingCapability 1
set_interface_property emif_axi writeIssuingCapability 1
set_interface_property emif_axi combinedIssuingCapability 1
set_interface_property emif_axi issuesINCRBursts true
set_interface_property emif_axi issuesWRAPBursts true
set_interface_property emif_axi issuesFIXEDBursts true
set_interface_property emif_axi ENABLED true
set_interface_property emif_axi EXPORT_OF ""
set_interface_property emif_axi PORT_NAME_MAP ""
set_interface_property emif_axi CMSIS_SVD_VARIABLES ""
set_interface_property emif_axi SVD_ADDRESS_GROUP ""
set_interface_property emif_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property emif_axi SV_INTERFACE_TYPE ""
set_interface_property emif_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port emif_axi emif_axi_arlock_o arlock Output 1
add_interface_port emif_axi emif_axi_arprot_o arprot Output 3
add_interface_port emif_axi emif_axi_arqos_o arqos Output 4
add_interface_port emif_axi emif_axi_arready_i arready Input 1
add_interface_port emif_axi emif_axi_arvalid_o arvalid Output 1
add_interface_port emif_axi emif_axi_araddr_o araddr Output 30
add_interface_port emif_axi emif_axi_arburst_o arburst Output 2
add_interface_port emif_axi emif_axi_arid_o arid Output 7
add_interface_port emif_axi emif_axi_arlen_o arlen Output 8
add_interface_port emif_axi emif_axi_arsize_o arsize Output 3
add_interface_port emif_axi emif_axi_aruser_o aruser Output 4
add_interface_port emif_axi emif_axi_rready_o rready Output 1
add_interface_port emif_axi emif_axi_rvalid_i rvalid Input 1
add_interface_port emif_axi emif_axi_rlast_i rlast Input 1
add_interface_port emif_axi emif_axi_rdata_i rdata Input 256
add_interface_port emif_axi emif_axi_rid_i rid Input 7
add_interface_port emif_axi emif_axi_rresp_i rresp Input 2
add_interface_port emif_axi emif_axi_ruser_i ruser Input 64
add_interface_port emif_axi emif_axi_awlock_o awlock Output 1
add_interface_port emif_axi emif_axi_awprot_o awprot Output 3
add_interface_port emif_axi emif_axi_awqos_o awqos Output 4
add_interface_port emif_axi emif_axi_awready_i awready Input 1
add_interface_port emif_axi emif_axi_awvalid_o awvalid Output 1
add_interface_port emif_axi emif_axi_awaddr_o awaddr Output 30
add_interface_port emif_axi emif_axi_awburst_o awburst Output 2
add_interface_port emif_axi emif_axi_awid_o awid Output 7
add_interface_port emif_axi emif_axi_awlen_o awlen Output 8
add_interface_port emif_axi emif_axi_awsize_o awsize Output 3
add_interface_port emif_axi emif_axi_awuser_o awuser Output 4
add_interface_port emif_axi emif_axi_wlast_o wlast Output 1
add_interface_port emif_axi emif_axi_wready_i wready Input 1
add_interface_port emif_axi emif_axi_wvalid_o wvalid Output 1
add_interface_port emif_axi emif_axi_wdata_o wdata Output 256
add_interface_port emif_axi emif_axi_wstrb_o wstrb Output 32
add_interface_port emif_axi emif_axi_wuser_o wuser Output 64
add_interface_port emif_axi emif_axi_bready_o bready Output 1
add_interface_port emif_axi emif_axi_bvalid_i bvalid Input 1
add_interface_port emif_axi emif_axi_bid_i bid Input 7
add_interface_port emif_axi emif_axi_bresp_i bresp Input 2

